version: "2.26"

services:
  client:
    image: ${{secrets.AWS_BASIC_URL}}/${{secrets.REPOSITORY}}:note-client
    container_name: note-client
    restart: always
    posrts:
      - "5173:5173"
    networks:
      - server

  api:
    image: ${{secrets.AWS_BASIC_URL}}/${{secrets.REPOSITORY}}:note-server
    container_name: note-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - server

  db:
    image: ${{secrets.AWS_BASIC_URL}}/${{secrets.REPOSITORY}}:db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: ${{secrets.DB_USER}}
      MYSQL_ROOT_PASSWORD: ${{secrets.DB_ROOT_PASSWORD}}
      MYSQL_PASSWORD: ${{secrets.DB_PASSWORD}}
      MYSQL_DATABASE: ${{secrets.DB_DATABASE}}

networks:
  server:

volumes:
  db_data: {}
